### PR TITLE
Remove cert manager subscription check

### PR DESCRIPTION
**Pull request by Daniel-Fan**

### CODE REVIEW

**Comment by Daniel-Fan** [comment]
@mandymchu 

Would you please review it again? We keep `SKIP_INSTALL` unchanged for cert-manager-webhook checking

**Review by mandymchu — APPROVED** [review]

**Comment by mandymchu** [comment]
lgtm
test passed for cert manager only, but the script at this moment failed to install licensing due to the package manifest name mismatched

**Comment by Daniel-Fan** [comment]
Thank you @mandymchu 

We will handle the licensing package name issue in a separate PR

**Review by YCShen1010 — APPROVED** [review]
/lgtm

**Pull request merged**
