### PR TITLE
align the subscription name on deleting Crossplane

### PR DESCRIPTION
**Pull request by Daniel-Fan**
missing prefix `ibm` when deleting the subscription #725

### CODE REVIEW

**Comment by ppyt-pl** [comment]
Your changes are ok, except for my mistake in operator packages names. I created comments. Please also change constants by adding `-app` suffix in following places:
https://github.com/Daniel-Fan/ibm-common-service-operator/blob/align-subscription-name/controllers/constant/crossplane.go#L66
https://github.com/Daniel-Fan/ibm-common-service-operator/blob/align-subscription-name/controllers/constant/crossplane.go#L71
https://github.com/Daniel-Fan/ibm-common-service-operator/blob/align-subscription-name/controllers/constant/crossplane.go#L92
https://github.com/Daniel-Fan/ibm-common-service-operator/blob/align-subscription-name/controllers/constant/crossplane.go#L97

**Comment by Daniel-Fan** [comment]
@ppyt-pl Thank you for reviewing and the comments.

I have updated the code. Could you please check it again when you are available? Thank you!

**Review by horis233 — APPROVED** [review]

**Comment by horis233** [comment]
@ppyt-pl Feel free to add the lgtm label if it looks good to you

**Pull request merged**
