### PR TITLE
Add rbac to kube-public

### PR DESCRIPTION
**Pull request by horis233**

### CODE REVIEW

**Comment by chenzhiwei** [comment]
please test this manually, and leave a comment if it can work, then I will approve and merge this PR.

**Comment by horis233** [comment]
@chenzhiwei 

It works for me when I install, I will collaborate with CP4I to check if the workaround works for them.

**Comment by horis233** [comment]
@zhiwei The workaround works for CP4I team

**Comment by renshichuang** [comment]
@liqlin2015  @yuwei  I think later we need to move this logic to mgmt ingress operator.  cc @chenzhiwei @horis233

**Pull request merged**
