### PR TITLE
fipsEnable

### PR DESCRIPTION
**Pull request by qpdpQ**

### CODE REVIEW

**Comment by qpdpQ** [comment]
this error is because fipsEnabledTemplate not exported by package constant

**Comment by qpdpQ** [comment]
this image can be used to verify: quay.io/yuchen_li1/common-service-operator-amd64@sha256:7aaea19add5324706f51d2e47f09f0e35f1fcac22f3d3c947b68810f8992c2c9

**Comment by qpdpQ** [comment]
In the current stage it works in:
global fipsEnable:
1. from empty to true or false
2. from true to false or false to true

fipsEnabled for single service:

1. from empty to true or false
2. from true to false or false to true

It still have issues on: 
global fipsEnable:
1. we set it to false and delete it, this logic will not bring it back to true

fipsEnabled for single service:
1. we set it to false and delete it, this logic will not bring it back to true

**Comment by qpdpQ** [comment]
don't merge for now, waiting for ingress team's research: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/55610

**Review by Daniel-Fan — APPROVED** [review]
/lgtm

**Pull request merged**
