### PR TITLE
added bitscuit to OWNERS

### PR DESCRIPTION
**Pull request by bitscuit**

### CODE REVIEW

**Review by Daniel-Fan — APPROVED** [review]
/lgtm

**Comment by Daniel-Fan** [comment]
@horis233 
I believe this PR needs the approval of you.

I will add myself to the OWNERS after this PR is merged in order to avoid conflict.

**Comment by horis233** [comment]
@bitscuit please add @Daniel-Fan and remove jinchun-dev

**Review by horis233 — APPROVED** [review]
/lgtm

**Pull request merged**
