### PR TITLE
Add Configuration as new type of Crossplane CR

### PR DESCRIPTION
**Pull request by ppyt-pl**

### CODE REVIEW

**Comment by ppyt-pl** [comment]
@horis233 could you please review the changes? It is still in progress so do not merge. Are labels/annotations needed in this yaml?

**Comment by horis233** [comment]
@ppyt-pl 

Could you run `make code-dev` in your code to eliminate the lint error?

**Comment by ppyt-pl** [comment]
Hi @horis233, this command results in
```
controllers/render_template.go:147:4: SA4006: this value of `configSize` is never used (staticcheck)
                        configSize = config
                        ^
make[1]: *** [common/Makefile.common.mk:48: lint-go] Error 123
make[1]: Leaving directory '/home/pp/ibm-common-service-operator'
make: [Makefile:163: code-dev] Error 2 (ignored)
```
even on master. I haven't changed this file.
It's probably caused by `golangci-lint`, I downloaded this release https://github.com/golangci/golangci-lint/releases/tag/v1.37.0 because newer ones produced other errors.

**Comment by ppyt-pl** [comment]
@horis233 It was related to linter version. Now it works, I fixed linter issues.

**Review by horis233 — APPROVED** [review]
/lgtm

**Comment by ppyt-pl** [comment]
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/48268

**Pull request merged**
