### PR TITLE
update pkg for twistlock

### PR DESCRIPTION
**Pull request by bluzarraga**

### CODE REVIEW

**Comment by bitscuit** [comment]
The changes for 3.23 fixpacks should go into `release-323` branch

**Comment by bluzarraga** [comment]
changed base to release-323

**Comment by bluzarraga** [comment]
seems to be a problem with the prow builds

**Comment by bluzarraga** [comment]
The check is failing with this error

> level=error msg="Running error: context loading failed: failed to load program with go/packages: could not parse GOARCH and Go compiler in format \"<GOARCH> <compiler>\" from stdout of go command:\nGOROOT=/usr/local/go GOPATH=/home/prow/go GO111MODULE=on PWD=/home/prow/go/src/github.com/IBM/ibm-common-service-operator go [list -f {{context.GOARCH}} {{context.Compiler}} -- unsafe]\ndir: /home/prow/go/src/github.com/IBM/ibm-common-service-operator\nstdout: <<>>\nstderr: <<verifying k8s.io/apimachinery@v0.18.6/go.mod: invalid GOSUMDB: malformed verifier id\n>>"

The exact same pr passed https://github.com/IBM/ibm-common-service-operator/pull/1030. I'm not sure what the issue is here.

**Comment by bluzarraga** [comment]
closing and recreating pr on advice from Xinchun

**Pull request closed without merging**
