### PR TITLE
convert operator itself's catalogsource

### PR DESCRIPTION
**Pull request by horis233**

### CODE REVIEW

**Comment by ZhuoxiLi** [comment]
just a suggestion, could we add a brief description of pr when necessary; such as, the pr is created for **which requirements OR which issue OR why we need it**. it will help reviewers get a clearer understanding

**Comment by horis233** [comment]
> just a suggestion, could we add a brief description of pr when necessary; such as, the pr is created for **which requirements OR which issue OR why we need it**. it will help reviewers get a clearer understanding

Sure This PR is for migrating from catalogsource opencloudio to ibm-operator-catalog. Not just for other children operators, ibm-common-service-operator needs to update the catalogsource itself as well.

**Review by Daniel-Fan — APPROVED** [review]
It looks good to me. Approve it.

Please feel free to add the `/lgtm` label.

**Pull request merged**
