### PR TITLE
add relatedImages to operator CSV

### PR DESCRIPTION
**Pull request by Daniel-Fan**

### CODE REVIEW

**Comment by Daniel-Fan** [comment]
@horis233 @ZhuoxiLi Since we have released CS 3.10, we could merge this PR now~

**Comment by Daniel-Fan** [comment]
The `rebase` conflict has been resolved

**Comment by horis233** [comment]
@Daniel-Fan Please rebase the issue again

**Comment by Daniel-Fan** [comment]
The issue has been resolved 💯

**Review by ZhuoxiLi — APPROVED** [review]
/lgtm

**Pull request merged**
