### PR TITLE
add new entry for ibm-platformui-operator

### PR DESCRIPTION
**Pull request by YCShen1010**
- Add new entry for `ibm-platformui-operator`
- Add new entry for `ibm-platformui-operator-v4.0`
- Update the corresponding OperandConfig templates

### CODE REVIEW

**Review by Daniel-Fan — APPROVED** [review]
/lgtm

**Review by Daniel-Fan — APPROVED** [review]
/lgtm

**Comment by YCShen1010** [comment]
issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/57206

**Pull request merged**
