### PR TITLE
allow all cs cr in any namespaces can enable crossplane operator

### PR DESCRIPTION
**Pull request by ZhuoxiLi**
Here is my design idea, feel free to give any suggestions.

### CODE REVIEW

**Review by Daniel-Fan — COMMENTED** [review]
The overall code structure looks great.

But I am confused that since `instance.Spec.Features.Bedrockshim` is controlling the installation of both `crossplane operator` and `cloud operator`. Should we include `cloud operator` installation in the reconciliation of all CRs?
If `Bedrockshim=true && SaasEnable=true` happens in any one of the CRs, not only in the `Master` CR, then we should install `cloud operator`.

The other point is we could find that in both `ReconcileMasterCR` and `ReconcileGeneralCR`, there is a parameter called `inScope`.
`inScope` is used to indicate whether the current reconciled CR is in the scope of cs-operator. Because in SaaS or multi-instance deployment, each cs-operator will still reconcile all the CommonService CRs in the cluster in order to get the configuration of cluster-scope resources in each CR like cert-manager and update its own namespace-scoped `OperandConfig`.

Therefore, when we check the `Bedrockshim` in the current CR, we should first check whether the CR is in the scope. If it is not in the scope, we should skip the installation.

**Comment by horis233** [comment]
> The overall code structure looks great.
> 
> But I am confused that since `instance.Spec.Features.Bedrockshim` is controlling the installation of both `crossplane operator` and `cloud operator`. Should we include `cloud operator` installation in the reconciliation of all CRs?
> If `Bedrockshim=true && SaasEnable=true` happens in any one of the CRs, not only in the `Master` CR, then we should install `cloud operator`.
> 
> The other point is we could find that in both `ReconcileMasterCR` and `ReconcileGeneralCR`, there is a parameter called `inScope`.
> `inScope` is used to indicate whether the current reconciled CR is in the scope of cs-operator. Because in SaaS or multi-instance deployment, each cs-operator will still reconcile all the CommonService CRs in the cluster in order to get the configuration of cluster-scope resources in each CR like cert-manager and update its own namespace-scoped `OperandConfig`.
> 
> Therefore, when we check the `Bedrockshim` in the current CR, we should first check whether the CR is in the scope. If it is not in the scope, we should skip the installation.

Thanks for your comment. I think so.

**Comment by ZhuoxiLi** [comment]
Thank you for the suggestions! Please review again @horis233 @Daniel-Fan

**Review by Daniel-Fan — APPROVED** [review]
/lgtm

**Pull request merged**
