### PR TITLE
Implement Concatenating OperandRegistry YAMLs

### PR DESCRIPTION
**Pull request by YCShen1010**
Introduced a new function `ConcatenateRegistries` essentially combines the `Operators` from two OperandRegistry objects and returns the concatenated YAML representation of the modified OperandRegistry.

for issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/58224

####  The function performs the following steps:

- It creates two OperandRegistry objects: `baseRegistry` and `insertedRegistry` by unmarshaling the YAML templates using the applyTemplate function.
- It appends the `Operators` from `insertedRegistry` to the existing `Operators` in `baseRegistry`.
- It marshals the modified base object back to YAML format using json.Marshal.
- It returns the resulting YAML string and any error that occurred during the process.

#### Verify
test image: quay.io/yuchen_shen/cs_operator:split_opreg
delete origin OprandRegistry and it will create a new one with the entries of CP2 and followed by the entries of CP3.

### CODE REVIEW

**Comment by Daniel-Fan** [comment]
Hold the PR, it would be merged together with ODLM's enhancement.

**Comment by YCShen1010** [comment]
Latest update:
- on-prem

  - in `CSV2OpReg`: `ibm-mongodb-operator` (no-op), `ibm-commonui-operator` (no-op), `ibm-iam-operator` (no-op), and `ibm-zen-operator` (no-op)
  - in `CSV3OpReg`: `ibm-mongodb-operator-v4.0`, `ibm-idp-config-ui-operator-v4.0`, `ibm-im-operator-v4.0`, `ibm-im-operator`, `ibm-platformui-operator-v4.0` and `ibm-platformui-operator`
  - `CSV3OperandRegistry` = `CSV2OpReg` + `CSV3OpReg`
- Saas
  - in `CSV2SaasOpReg`: `ibm-mongodb-operator` (no-op), `ibm-iam-operator` (no-op), and `ibm-zen-operator` (no-op)
  - in `CSV3SaasOpReg`: `ibm-mongodb-operator-v4.0`， `ibm-im-operator-v4.0`, `ibm-im-operator`, `ibm-platformui-operator-v4.0` and `ibm-platformui-operator`
  - `CSV3SaasOperandRegistry` = `CSV2SaasOpReg` + `CSV3SaasOpReg`

**Comment by Daniel-Fan** [comment]
@YCShen1010 
Could we update the OperandConfig for `ibm-im-operator` and `ibm-im-operator-v4.0`?
It's OperandRequest should include CP3 MongoDB and CommonUI.

I believe we could try to play some tricks on this
```
- name: ibm-im-operator
  spec:
    operandRequest:
      requests:
        - operands:
            - name: ibm-mongodb-operator-{{ .Channel }}
            - name: ibm-idp-config-ui-operator-{{ .Channel }}
- name: ibm-im-operator-v4.0
  spec:
    operandRequest:
      requests:
        - operands:
            - name: ibm-mongodb-operator-v4.0
            - name: ibm-idp-config-ui-operator-v4.0
```

**Comment by Daniel-Fan** [comment]
Test and verified that Bedrock and Zen could be installed successfully.

**Review by Daniel-Fan — APPROVED** [review]
/lgtm

**Pull request merged**
