### PR TITLE
updated channel switch messages

### PR DESCRIPTION
**Pull request by pgodowski**
minor updates to the user facing messages

### CODE REVIEW

**Comment by davesoroka** [comment]
Those strings look like hard coded English strings.  Are these exempt from translation?

**Comment by pgodowski** [comment]
@horis233 do we have any g11n method for this script?

**Comment by horis233** [comment]
@pgodowski @davesoroka We don't have g11n method for this script.
If we need to support multiple languages, we can ask ID to provide translations. When using the script, users can specify the language with a parameter like `--LANG=zh_CN`.

**Comment by davesoroka** [comment]
it's not something for us to fix for this release.  But we should talk through translation requirements for the next release.

**Review by horis233 — APPROVED** [review]
/lgtm

**Pull request merged**
