### PR TITLE
support upgrade for simple and all namespaces mode

### PR DESCRIPTION
**Pull request by Daniel-Fan**
`setup_tenant.sh` would support upgrade inside v4.x version e.g., from `v4.0` to `v4.1` for simple and all namespace topology

### Test with simple topology fresh installation
- It is still NOT allowed
```
./cp3pt0-deployment/setup_tenant.sh --license-accept -c v4.0 --operator-namespace cloudpak-simple    

# Start to validate the parameters passed into script... 
[✔] oc command available
[✔] yq command available
[✔] oc command logged in as kube:admin
[✔] Channel is valid
[INFO] CommonService CRD exists but main CommonService CR does not exist, skipping defaulting from original CommonService CR

[✗] It is simple topology or all namespaces topology

[✔] Profile size is not specified. Use default value: starterset
[✘] Must provide additional namespaces for --tethered-namespaces or --excluded-namespaces when services-namespace is the same as operator-namespace
```

### Test with simple topology upgrade
- Upgrade for simple topology is allowed
- No NamespaceScope Operator will be configured
```
./cp3pt0-deployment/setup_tenant.sh --license-accept -c v4.1 --operator-namespace cloudpak-simple 

# Start to validate the parameters passed into script... 
[✔] oc command available
[✔] yq command available
[✔] oc command logged in as kube:admin
[✔] Channel is valid
[✗] It is simple topology or all namespaces topology

[✔] Profile size is valid.
...

[✗] NamespaceScope Configuration is not needed for simple or all namespaces topology, skip NamespaceScope setup

# Installing IBM Foundational services operator into operator namespace cloudpak-simple...
# Checking if CommonService CRD exists in the cluster...
[INFO] CommonService CRD exist

# Configuring CommonService CR in cloudpak-simple...
[INFO] Configuring CommonService CR common-service in cloudpak-simple

apiVersion: operator.ibm.com/v3
kind: CommonService
metadata:
  annotations:
    version: "-1"
  name: common-service
  namespace: cloudpak-simple
spec:
  license:
    accept: false
  operatorNamespace: cloudpak-simple
  servicesNamespace: cloudpak-simple
  size: starterset
status:
  configStatus:
    catalogName: opencloud-operators
    catalogNamespace: openshift-marketplace
    configurable: true
    operatorDeployed: true
    operatorNamespace: cloudpak-simple
    servicesDeployed: true
    servicesNamespace: cloudpak-simple
    topologyConfigurableCRs:
      - apiVersion: operator.ibm.com/v3
        kind: CommonService
        namespace: cloudpak-simple
        objectName: common-service
  overallStatus: Succeeded
  phase: Succeeded

Warning: resource commonservices/common-service is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by oc apply. oc apply should only be used on resources created declaratively by either oc create --save-config or oc apply. The missing annotation will be patched automatically.
commonservice.operator.ibm.com/common-service configured
[✔] Successfully patched CommonService CR in cloudpak-simple
```

### Test with complex topology fresh installation
- Work as usual
```
./cp3pt0-deployment/setup_tenant.sh --license-accept -c v4.0 --operator-namespace cloudpak-control-2 --services-namespace cloudpak-data-2  

# Start to validate the parameters passed into script... 
[✔] oc command available
[✔] yq command available
[✔] oc command logged in as kube:admin
[✔] Channel is valid
[INFO] CommonService CRD exists but main CommonService CR does not exist, skipping defaulting from original CommonService CR

[✔] Profile size is not specified. Use default value: starterset

# Checking whether Namespace cloudpak-control-2 exist...
[INFO] Creating namespace cloudpak-control-2
namespace/cloudpak-control-2 created
[INFO] Waiting for project cloudpak-control-2 to be created
[✔] Project cloudpak-control-2 is created

# Checking whether Namespace cloudpak-data-2 exist...
[INFO] Creating namespace cloudpak-data-2
namespace/cloudpak-data-2 created
[INFO] Waiting for project cloudpak-data-2 to be created
[✔] Project cloudpak-data-2 is created
...
```

### Test with complex topology upgrade
- Only `--operator-namespace` is required
- Upgrade both namespaceScope operator and ibm common service operator
```
./cp3pt0-deployment/setup_tenant.sh --license-accept -c v4.1 --operator-namespace cloudpak-control-2 

# Start to validate the parameters passed into script... 
[✔] oc command available
[✔] yq command available
[✔] oc command logged in as kube:admin
[✔] Channel is valid
[✔] Profile size is valid.
...

# Updating ibm-namespace-scope-operator in namesapce cloudpak-control-2...
[INFO] v4.0 is less than v4.1
[INFO] catalogsource opencloud-operators is the same as opencloud-operators
[INFO] ibm-namespace-scope-operator is ready for updating the subscription.
subscription.operators.coreos.com/ibm-namespace-scope-operator configured
[✔] Successfully patched subscription ibm-namespace-scope-operator in cloudpak-control-2
[INFO] Waiting for operator ibm-namespace-scope-operator to be upgraded
...

# Updating ibm-common-service-operator in namesapce cloudpak-control-2...
[INFO] v4.1 is equal to v4.1
[INFO] catalogsource opencloud-operators is the same as opencloud-operators
[INFO] ibm-common-service-operator has already updated channel v4.1 and catalogsource opencloud-operators in the subscription.
subscription.operators.coreos.com/ibm-common-service-operator configured
[✔] Successfully patched subscription ibm-common-service-operator in cloudpak-control-2
[INFO] Waiting for operator ibm-common-service-operator to be upgraded
[✔] Operator ibm-common-service-operator is upgraded to latest version in channel v4.1

[INFO] Waiting for operator ibm-common-service-operator in namespace cloudpak-control-2 to be made available
[✔] Operator ibm-common-service-operator in namespace cloudpak-control-2 is available
```

### Test with all namespaces mode upgrade
- Only `--operator-namespace` is required
- Upgrade for all Namespaces mode is allowed
- No NamespaceScope Operator will be configured
```
./cp3pt0-deployment/setup_tenant.sh --license-accept -c v4.1 --operator-namespace openshift-operators

# Start to validate the parameters passed into script... 
[✔] oc command available
[✔] yq command available
[✔] oc command logged in as kube:admin
[✔] Channel is valid
[✗] It is all namespaces topology
...

[✗] NamespaceScope Configuration is not needed for simple or all namespaces topology, skip NamespaceScope setup

# Installing IBM Foundational services operator into operator namespace openshift-operators...
# Checking if CommonService CRD exists in the cluster...
[INFO] CommonService CRD exist

# Configuring CommonService CR in openshift-operators...
[INFO] Configuring CommonService CR common-service in openshift-operators

apiVersion: operator.ibm.com/v3
kind: CommonService
metadata:
  annotations:
    version: "-1"
  name: common-service
  namespace: openshift-operators
spec:
  license:
    accept: false
  operatorNamespace: openshift-operators
  servicesNamespace: ibm-common-services
  size: starterset
status:
  configStatus:
    catalogName: opencloud-operators
    catalogNamespace: openshift-marketplace
    configurable: true
    operatorDeployed: true
    operatorNamespace: openshift-operators
    servicesDeployed: true
    servicesNamespace: ibm-common-services
    topologyConfigurableCRs:
      - apiVersion: operator.ibm.com/v3
        kind: CommonService
        namespace: openshift-operators
        objectName: common-service
  overallStatus: Succeeded
  phase: Succeeded

Warning: resource commonservices/common-service is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by oc apply. oc apply should only be used on resources created declaratively by either oc create --save-config or oc apply. The missing annotation will be patched automatically.
commonservice.operator.ibm.com/common-service configured
[✔] Successfully patched CommonService CR in openshift-operators

# Checking whether IBM Common Service operator exist...
[INFO] There is an ibm-common-service-operator Subscription already

# Updating ibm-common-service-operator in namesapce openshift-operators...
[INFO] v4.0 is less than v4.1
[INFO] catalogsource opencloud-operators is the same as opencloud-operators
[INFO] ibm-common-service-operator is ready for updating the subscription.
Warning: resource subscriptions/ibm-common-service-operator is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by oc apply. oc apply should only be used on resources created declaratively by either oc create --save-config or oc apply. The missing annotation will be patched automatically.
subscription.operators.coreos.com/ibm-common-service-operator configured
[✔] Successfully patched subscription ibm-common-service-operator in openshift-operators
[INFO] Waiting for operator ibm-common-service-operator to be upgraded
[✔] Operator ibm-common-service-operator is upgraded to latest version in channel v4.1

[INFO] Waiting for operator ibm-common-service-operator in namespace openshift-operators to be made available
[✔] Operator ibm-common-service-operator in namespace openshift-operators is available
```

### CODE REVIEW

**Comment by bluzarraga** [comment]
Test case 1 passed
```
[root@api.promo.cp.fyre.ibm.com ibm-common-service-operator]# ./cp3pt0-deployment/setup_tenant.sh --license-accept -c v4.0 --operator-namespace cloudpak-simple

# Start to validate the parameters passed into script... 
[✔] oc command available
[✔] yq command available
[✔] oc command logged in as kube:admin
[✔] Channel is valid
[INFO] CommonService CRD exists but main CommonService CR does not exist, skipping defaulting from original CommonService CR

[✗] It is simple topology or all namespaces topology

[✔] Profile size is not specified. Use default value: starterset
[✘] Must provide additional namespaces for --tethered-namespaces or --excluded-namespaces when services-namespace is the same as operator-namespace
[root@api.promo.cp.fyre.ibm.com ibm-common-service-operator]# 
```

Test case 2 passed, script completed as expected, upgrade to 4.1 successful
Test case 3 passed, script completed as expected, install successful
Test case 4 passed, script completed as expected and upgrade succeeded. I had to run test case 4 twice though. The first time the script exited after waiting for cs operator to come ready as it seemingly could not access the cloudpak-data-2 namespace. Rerunning the script solved the problem
Test case 5 passed, script completed as expected and upgrade to 4.1 was successful

**Comment by bluzarraga** [comment]
@Daniel-Fan I'm going to approve with the hold label since I think this looks good but you may feel differently about the test case 4 needing a second run through. If not feel free to remove the hold label

**Comment by Daniel-Fan** [comment]
Hi @bluzarraga 

Thank you for testing this!

Yeah, I think the test case 4 is a known issue that OLM does not propagate `WATCH_NAMESPACE` from CSV to deployment.

We have a script issue opened to make further enhancement. https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59565
And we have a troubleshooting topic ready as well. https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59567

**Comment by bluzarraga** [comment]
@Daniel-Fan yeah it was the same issue, ok cool I'll remove the hold label

**Pull request merged**
